[theme]
primaryColor = "#0d1b2a"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1b263b"
textColor = "#e0e1dd"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "auto"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
